// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["jquery", "bootstrap", "backbone"], function($, Bootstrap, Backbone) {
    var BaseView;
    return BaseView = (function(superClass) {
      extend(BaseView, superClass);

      function BaseView() {
        return BaseView.__super__.constructor.apply(this, arguments);
      }

      BaseView.prototype.render = function() {
        var data;
        data = {
          collection: this.collection ? this.collection || {} : void 0
        };
        _.each(this.tmplHelpers, (function(_this) {
          return function(helper, name) {
            return _this.tmplHelpers[name] = _.template(helper);
          };
        })(this));
        _.extend(data, this.tmplHelpers);
        console.debug("data", this.tmplHelpers);
        return this.$el.empty().html(_.template(this.tmpl)(data));
      };

      BaseView.prototype.renderError = function(message) {
        var code, msg, res;
        code = null;
        if (res = message.base_rsp) {
          code = res.ret;
          msg = res.msg;
        }
        return this.$el.html("<br />\n<div class=\"text-center text-danger\">\n    <h3 class=\"\"> ERROR " + (code || "") + "</h3>\n    <p class=\"\">" + (msg || message) + "</p>\n</div>");
      };

      BaseView.prototype.renderLoading = function(msg) {
        if (msg == null) {
          msg = "Loading...";
        }
        return this.$el.html("<br />\n<p class=\"text-center\"> " + msg + " </p>");
      };

      return BaseView;

    })(Backbone.View);
  });

}).call(this);
