// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["views/baseView"], function(BaseView) {
    var Portal;
    return Portal = (function(superClass) {
      extend(Portal, superClass);

      function Portal() {
        return Portal.__super__.constructor.apply(this, arguments);
      }

      Portal.prototype.className = "container";

      Portal.prototype.initialize = function() {
        return this.render();
      };

      Portal.prototype.collection = {
        location: "深圳",
        craftList: [
          {
            craftPhotoUrl: "#craft/1",
            craftName: "1",
            artistsAmount: 1,
            star: "1",
            craftID: "1"
          }
        ]
      };

      Portal.prototype.tmplHelpers = {
        craftItem: "<div class=\"row craft-item\" data-craft-id=<%-craftID%>>\n    <div class=\"craft-main-photo col-xs-4\">\n        <image src=\"<%-craftPhotoUrl%>\">\n    </div>\n    <div class=\"craft-basic-info col-xs-6\">\n        <div class=\"craft-name \"><%-craftName%></div>\n        <div class=\"craft-detail-unit\"><%-artistsAmount%>人</div>\n        <div class=\"craft-detail-unit\">今日之星:<%-star%></div>\n    </div>\n    <div class=\"craft-access col-xs-2\">\n        <a href=\"\">进入</a>\n    </div>\n</div>"
      };

      Portal.prototype.tmpl = "<nav class=\"top-nav row navbar-fixed-top\">\n    <div class=\"district-selector col-xs-4 text-center\"><%-collection.location%><span down-arrow></span></div>\n    <div class=\"user-link col-xs-4 text-center\">我</div>\n</nav>\n<div class=\"craft-list\">\n    <div>\n        <% _.each(collection.craftList, function(item){ print(craftItem(item)) })%>\n    <div>\n</div>";

      return Portal;

    })(BaseView);
  });

}).call(this);
